#!/usr/bin/expect -f

#starts guest vm, run benchmarks, poweroff
set timeout -1
set kernel_dir [lindex $argv 0]
set driver_dir [lindex $argv 1]
set cpu_num [lindex $argv 2]
set memory_size [lindex $argv 3]
set cpu_set [lindex $argv 4]

set vector_num [expr {$cpu_num * 2 + 2}]

#Start migration target
spawn sudo env FM2_IS_SOURCE_VM=0 taskset -c $cpu_set \
		qemu-system-x86_64 \
		--enable-kvm \
        -name dest_vm \
		-cpu host \
        -global kvm-apic.vapic=off \
		-smp $cpu_num \
		-m $memory_size \
		-kernel $kernel_dir/arch/x86_64/boot/bzImage \
		-nographic -serial mon:stdio \
		-drive file=$driver_dir/bullseye.img,format=raw \
		-append "console=ttyS0 root=/dev/sda earlyprintk=serial net.ifnames=0" \
		-netdev tap,id=ens1f0,ifname=tap1,script=no,downscript=no,vhost=off,queues=$cpu_num \
		-device virtio-net,netdev=ens1f0,mac=52:55:00:d1:55:01,mq=on,vectors=$vector_num \
		-incoming defer \
		-monitor unix:qemu-monitor-migration-dst,server,nowait

interact
